export const data = [
  {
    id: 2,
    attributes: {
      createdAt: "2022-10-26T14:12:00.479Z",
      updatedAt: "2022-10-27T18:00:02.383Z",
      publishedAt: "2022-10-26T14:12:18.152Z",
      title: "FastTrade Pro ",
      price: 99.9,
      description:
        "O Fast Trade é uma plataforma com ferramentas de Tape Reading dentro dos seus módulos, por exemplo: Livro de Ofertas, Agressores, Times & Trades, Volume at Price e outros para acompanhar os mercados financeiros.\n",
      informative_text: "*Demonstrativo: 7 dias",
      buy_button_label: "Contratar",
      locale: "en",
      price_text: "R$99,90/mês",
      developer: {
        data: {
          id: 2,
          attributes: {
            name: "Cellbroker",
            createdAt: "2022-10-26T14:00:56.539Z",
            updatedAt: "2022-10-26T14:12:42.494Z",
            publishedAt: "2022-10-26T14:12:42.492Z",
          },
        },
      },
      image: {
        data: {
          id: 7,
          attributes: {
            name: "plataforma-fasttrade-pro (1).png",
            alternativeText: "plataforma-fasttrade-pro (1).png",
            caption: "plataforma-fasttrade-pro (1).png",
            width: 391,
            height: 236,
            formats: {
              thumbnail: {
                ext: ".png",
                url: "/uploads/thumbnail_plataforma_fasttrade_pro_1_cac4ed9df8.png",
                hash: "thumbnail_plataforma_fasttrade_pro_1_cac4ed9df8",
                mime: "image/png",
                name: "thumbnail_plataforma-fasttrade-pro (1).png",
                path: null,
                size: 63.04,
                width: 245,
                height: 148,
              },
            },
            hash: "plataforma_fasttrade_pro_1_cac4ed9df8",
            ext: ".png",
            mime: "image/png",
            size: 112.13,
            url: "/uploads/plataforma_fasttrade_pro_1_cac4ed9df8.png",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2022-10-26T14:07:13.890Z",
            updatedAt: "2022-10-26T14:11:24.979Z",
          },
        },
      },
      localizations: {
        data: [],
      },
    },
  },
  {
    id: 3,
    attributes: {
      createdAt: "2022-10-26T15:30:56.112Z",
      updatedAt: "2022-10-27T18:00:15.721Z",
      publishedAt: "2022-10-26T15:32:21.735Z",
      title: "Tryd Trader",
      price: 79.9,
      description:
        "O Tryd Trader é uma solução para o trader que precisa de uma plataforma profissional com agilidade e acompanhamento em tempo real de notícias, análises, cotações, ferramentas e gráficos integrados em um único ambiente.\n\n",
      informative_text: "*Demonstrativo: 30 dias.",
      buy_button_label: "Contrate",
      locale: "en",
      price_text: "R$79,90/mês",
      developer: {
        data: {
          id: 4,
          attributes: {
            name: "Plug and Trade",
            createdAt: "2022-10-26T14:01:34.244Z",
            updatedAt: "2022-10-26T14:12:46.960Z",
            publishedAt: "2022-10-26T14:12:46.959Z",
          },
        },
      },
      image: {
        data: {
          id: 4,
          attributes: {
            name: "plataforma-tryd-trader.png",
            alternativeText: "plataforma-tryd-trader.png",
            caption: "plataforma-tryd-trader.png",
            width: 390,
            height: 227,
            formats: {
              thumbnail: {
                ext: ".png",
                url: "/uploads/thumbnail_plataforma_tryd_trader_e14c44ec58.png",
                hash: "thumbnail_plataforma_tryd_trader_e14c44ec58",
                mime: "image/png",
                name: "thumbnail_plataforma-tryd-trader.png",
                path: null,
                size: 54.5,
                width: 245,
                height: 143,
              },
            },
            hash: "plataforma_tryd_trader_e14c44ec58",
            ext: ".png",
            mime: "image/png",
            size: 96.33,
            url: "/uploads/plataforma_tryd_trader_e14c44ec58.png",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2022-10-26T14:07:13.857Z",
            updatedAt: "2022-10-26T15:30:32.492Z",
          },
        },
      },
      localizations: {
        data: [],
      },
    },
  },
  {
    id: 4,
    attributes: {
      createdAt: "2022-10-26T18:05:50.489Z",
      updatedAt: "2022-10-27T18:00:22.469Z",
      publishedAt: "2022-10-26T18:05:51.324Z",
      title: "Profit One",
      price: 89.9,
      description:
        "O ProfitOne é uma solução para o trader que busca recursos para analise técnica com diversas periodicidades gráficas, desde o modelo simples até gráfico de Renko.\n\n",
      informative_text: "*Demonstrativo: 15 dias.",
      buy_button_label: "Contrate",
      locale: "en",
      price_text: "R$89,90/mês",
      developer: {
        data: {
          id: 3,
          attributes: {
            name: "Nelogica",
            createdAt: "2022-10-26T14:01:27.974Z",
            updatedAt: "2022-10-26T14:12:44.617Z",
            publishedAt: "2022-10-26T14:12:44.616Z",
          },
        },
      },
      image: {
        data: {
          id: 8,
          attributes: {
            name: "plataforma-profit-one.png",
            alternativeText: "plataforma-profit-one.png",
            caption: "plataforma-profit-one.png",
            width: 390,
            height: 227,
            formats: {
              thumbnail: {
                ext: ".png",
                url: "/uploads/thumbnail_plataforma_profit_one_3c6e0a0d75.png",
                hash: "thumbnail_plataforma_profit_one_3c6e0a0d75",
                mime: "image/png",
                name: "thumbnail_plataforma-profit-one.png",
                path: null,
                size: 53.51,
                width: 245,
                height: 143,
              },
            },
            hash: "plataforma_profit_one_3c6e0a0d75",
            ext: ".png",
            mime: "image/png",
            size: 96.36,
            url: "/uploads/plataforma_profit_one_3c6e0a0d75.png",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2022-10-26T18:04:35.760Z",
            updatedAt: "2022-10-26T18:04:35.760Z",
          },
        },
      },
      localizations: {
        data: [],
      },
    },
  },
  {
    id: 5,
    attributes: {
      createdAt: "2022-10-26T18:06:08.650Z",
      updatedAt: "2022-10-27T18:05:18.518Z",
      publishedAt: "2022-10-26T18:06:12.199Z",
      title: "Profit Plus",
      price: 150,
      description:
        "A versão Plus possui muitas ferramentas para o trader que busca agilidade e eficiência em suas operações, contando com ferramentas para Tape Reading e acesso gratuito ao Mobile da Nelogica.\n\n",
      informative_text: "*Demonstrativo: 15 dias.",
      buy_button_label: "Contratar",
      locale: "en",
      price_text: "R$150/mês",
      developer: {
        data: {
          id: 1,
          attributes: {
            name: "Cedro",
            createdAt: "2022-10-26T14:00:06.955Z",
            updatedAt: "2022-10-26T14:12:38.589Z",
            publishedAt: "2022-10-26T14:12:38.588Z",
          },
        },
      },
      image: {
        data: {
          id: 9,
          attributes: {
            name: "plataforma-profit-plus.png",
            alternativeText: "plataforma-profit-plus.png",
            caption: "plataforma-profit-plus.png",
            width: 390,
            height: 227,
            formats: {
              thumbnail: {
                ext: ".png",
                url: "/uploads/thumbnail_plataforma_profit_plus_abf698b4a7.png",
                hash: "thumbnail_plataforma_profit_plus_abf698b4a7",
                mime: "image/png",
                name: "thumbnail_plataforma-profit-plus.png",
                path: null,
                size: 66.69,
                width: 245,
                height: 143,
              },
            },
            hash: "plataforma_profit_plus_abf698b4a7",
            ext: ".png",
            mime: "image/png",
            size: 121.45,
            url: "/uploads/plataforma_profit_plus_abf698b4a7.png",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2022-10-26T18:04:35.763Z",
            updatedAt: "2022-10-26T18:04:35.763Z",
          },
        },
      },
      localizations: {
        data: [],
      },
    },
  },
  {
    id: 1,
    attributes: {
      createdAt: "2022-10-26T14:10:52.958Z",
      updatedAt: "2022-10-27T18:05:55.840Z",
      publishedAt: "2022-10-26T14:12:22.703Z",
      title: "Start Trade",
      price: 39.9,
      description:
        "Versão Start da Fast trade na medida para atender o trader que procura custo benefício aliados a boas funcionalidades gráficas, ferramentas como Times & Trades, Chart Trading, Resumo das Bolsas entre outros.",
      informative_text: "*Demonstrativo: 7 dias",
      buy_button_label: "Contratar",
      locale: "en",
      price_text: "R$39.90/mês",
      developer: {
        data: {
          id: 1,
          attributes: {
            name: "Cedro",
            createdAt: "2022-10-26T14:00:06.955Z",
            updatedAt: "2022-10-26T14:12:38.589Z",
            publishedAt: "2022-10-26T14:12:38.588Z",
          },
        },
      },
      image: {
        data: {
          id: 3,
          attributes: {
            name: "image 11.png",
            alternativeText: "start-trade.png",
            caption: "image 11.png",
            width: 266,
            height: 153,
            formats: {
              thumbnail: {
                ext: ".png",
                url: "/uploads/thumbnail_image_11_e2074bf892.png",
                hash: "thumbnail_image_11_e2074bf892",
                mime: "image/png",
                name: "thumbnail_image 11.png",
                path: null,
                size: 35.06,
                width: 245,
                height: 141,
              },
            },
            hash: "image_11_e2074bf892",
            ext: ".png",
            mime: "image/png",
            size: 32.07,
            url: "/uploads/image_11_e2074bf892.png",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2022-10-26T14:05:16.184Z",
            updatedAt: "2022-10-26T14:09:55.792Z",
          },
        },
      },
      localizations: {
        data: [],
      },
    },
  },
];
